"""python build.py  ->  regenerates every OBJ, meta.json and the verification PNGs in the parent folder.

Pipeline: model.pieces() (right leg, cells, hip origin) -> mirror for the left leg -> group by
segment x colour -> OBJ (studs, UVs 1 repeat = 4 studs) -> render FRONT/SIDE/BACK into the sheet's
pixel frame and compare with refs/255.png (silhouette IoU + per-colour IoU) -> hero 3/4 render.
"""
import json
import math
import os

import numpy as np
from PIL import Image, ImageDraw

import model
import render
from meshlib import Mesh, combine, open_edges, write_obj

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, ".."))
CELL = 0.816  # studs per grid cell (Scale 1.7 x 0.48)
SEGMENTS = ["Thigh", "Shin", "Foot"]
COLOURS = ["White", "Gold", "Blue", "Joint"]
HIP_X = render.HIP_X_CELLS  # 2.391 cells = 1.951 studs: |hip centre x| of each leg from the mech centre
HIP_H = -model.YG  # 10.368 cells = 8.460 studs: hip centre above the soles


def scaled(m, k, mirror=False):
    out = Mesh()
    out.v = [[(-p[0] if mirror else p[0]) * k, p[1] * k, p[2] * k] for p in m.v]
    out.f = [(a, c, b) for a, b, c in m.f] if mirror else list(m.f)
    return out


def r3(v):
    return [round(float(x), 4) for x in v]


def main():
    pieces = model.pieces()
    for seg, col, name, m in pieces:
        assert open_edges(m) == 0, name
    meta = {
        "units": "studs (1 grid cell of the sheet = 0.816 studs, mech Scale 1.7)",
        "frame": "each leg's own frame: origin = its HIP joint centre, +Y up, -Z forward (front faces -Z), +X = mech right",
        "hip_offsets_from_mech_centre": {"Leg_R": [round(HIP_X * CELL, 4), 0.0, 0.0], "Leg_L": [round(-HIP_X * CELL, 4), 0.0, 0.0]},
        "hip_height_above_ground": round(HIP_H * CELL, 4),
        "hip_spacing": round(2 * HIP_X * CELL, 4),
        "colours_rgb": {k: list(render.COLOURS[k]) for k in COLOURS},
        "legs": {},
    }
    summary = []
    for leg, mirror in (("R", False), ("L", True)):
        sx = -1 if mirror else 1
        joints = {"Hip": model.HIP, "Knee": model.KNEE, "Ankle": model.ANKLE}
        L = {"pivots": {k: r3((sx * v[0] * CELL, v[1] * CELL, v[2] * CELL)) for k, v in joints.items()},
             "segment_pivot": {"Thigh": "Hip", "Shin": "Knee", "Foot": "Ankle"}, "files": {}}
        groups = {}
        for seg, col, name, m in pieces:
            groups.setdefault((seg, col), []).append((name, m))
            groups.setdefault((None, col), []).append((name, m))
        for (seg, col), lst in sorted(groups.items(), key=lambda kv: (kv[0][0] or "", kv[0][1])):
            mm = scaled(combine(*[m for _, m in lst]), CELL, mirror)
            fname = "Leg_%s_%s%s.obj" % (leg, (seg + "_") if seg else "", col)
            V, F = mm.arrays()
            lo, hi = V.min(0), V.max(0)
            pivot = L["pivots"][L["segment_pivot"][seg]] if seg else [0.0, 0.0, 0.0]
            hdr = ("mech2 legs - %s  (generated by source/build.py; do not edit by hand)\n"
                   "frame: Leg_%s hip-joint centre = origin, studs, +Y up, -Z forward\n"
                   "segment: %s  colour: %s RGB %s  pieces: %s\n"
                   "bbox centre in leg frame: %s  size: %s\n"
                   "segment pivot (%s) in leg frame: %s" % (
                       fname, leg, seg or "whole leg", col, render.COLOURS[col], ", ".join(n for n, _ in lst),
                       r3((lo + hi) / 2), r3(hi - lo), (L["segment_pivot"][seg] if seg else "Hip"), pivot))
            ntri, stretch, nisl = write_obj(os.path.join(OUT, fname), mm, hdr)
            oe = open_edges(mm)
            L["files"][fname] = {"segment": seg or "All", "colour": col, "pieces": [n for n, _ in lst], "tris": ntri,
                                 "open_edges": oe, "uv_islands": nisl, "uv_max_stretch": round(stretch, 3),
                                 "bbox_centre": r3((lo + hi) / 2), "bbox_size": r3(hi - lo),
                                 "pivot": pivot, "bbox_centre_minus_pivot": r3((lo + hi) / 2 - np.array(pivot))}
            summary.append((fname, ntri, oe, stretch))
        meta["legs"]["Leg_" + leg] = L

    # ---------------- verification renders (both legs in mech space, cells)
    items = []
    for seg, col, name, m in pieces:
        V, F = m.arrays()
        for s in (1, -1):
            VV = V.copy()
            VV[:, 0] = s * VV[:, 0] + s * HIP_X
            items.append((VV, F if s == 1 else F[:, ::-1], col))
    res, ref = render.evaluate(items)
    meta["verification"] = {}
    paths = []
    for v in ("front", "side", "back"):
        r = res[v]
        p = os.path.join(OUT, "Legs_compare_%s.png" % v)
        render.compare_image(v, res, ref, p, scale=3)
        paths.append(p)
        meta["verification"][v] = {"silhouette_iou": round(r["iou"], 4),
                                   "colour_iou": {k: round(float(x), 3) for k, x in r["colour_iou"].items()},
                                   "colour_agreement": round(r["colour_agree"], 3)}
        print("%-5s IoU %.3f  colour agree %.2f  %s" % (v, r["iou"], r["colour_agree"],
                                                        {k: round(float(x), 2) for k, x in r["colour_iou"].items()}))
    ims = [Image.open(p) for p in paths]
    W = max(i.width for i in ims)
    allim = Image.new("RGB", (W, sum(i.height for i in ims)), "white")
    y = 0
    for i in ims:
        allim.paste(i, (0, y))
        y += i.height
    allim.save(os.path.join(OUT, "Legs_compare_all.png"))
    hero(items, os.path.join(OUT, "Legs_hero.png"))
    hero_segments(pieces, os.path.join(OUT, "Legs_segments.png"))

    meta["files_total"] = len(summary)
    with open(os.path.join(OUT, "meta.json"), "w") as fh:
        json.dump(meta, fh, indent=1)
    for f, n, oe, st in summary:
        print("%-28s %5d tris  open %d  stretch %.2f" % (f, n, oe, st))


def view_fn(yaw, pitch, s, cx, cy):
    cy_, sy_ = math.cos(math.radians(yaw)), math.sin(math.radians(yaw))
    cp, sp = math.cos(math.radians(pitch)), math.sin(math.radians(pitch))

    def fn(X, Y, Z):
        # camera in front-left-above (yaw about Y, then pitch down); depth = distance toward the camera
        x1 = X * cy_ + Z * sy_
        z1 = -X * sy_ + Z * cy_
        y2 = Y * cp + z1 * sp  # camera above: nearer (-z) points drop on screen
        z2 = -Y * sp + z1 * cp  # depth: smaller = nearer the camera
        return (cx - x1 * s, cy - y2 * s, z2)
    return fn


def hero(items, path):
    shots = []
    for yaw, pitch in ((-35, 15), (145, 15)):
        fn = view_fn(yaw, pitch, 34, 300, 90)
        img, m, _ = render.raster(items, None, (560, 600), ss=2, fn=fn, light=(-0.5, 0.6, -0.65), ink=True)
        shots.append(img)
    out = Image.new("RGB", (1200, 590), (228, 228, 228))
    for i, s in enumerate(shots):
        out.paste(Image.fromarray(np.clip(s, 0, 255).astype("uint8")), (i * 600, 30))
    d = ImageDraw.Draw(out)
    d.text((8, 8), "mech2 legs - 3/4 front-left and 3/4 back-right (orthographic, flat colours, ink = creases/colour edges)", fill=(0, 0, 0))
    out.save(path)


def hero_segments(pieces, path):
    """Exploded view: thigh / shin / foot pulled apart at their pivots (right leg)."""
    off = {"Thigh": (0, 0.0, 0), "Shin": (0, -1.2, 0), "Foot": (0, -2.4, 0)}
    items = []
    for seg, col, name, m in pieces:
        V, F = m.arrays()
        items.append((V + np.array(off[seg]), F, col))
    piv = [(model.HIP, "Thigh"), (model.KNEE, "Shin"), (model.ANKLE, "Foot")]
    fn = view_fn(-50, 12, 32, 300, 70)
    img, m, _ = render.raster(items, None, (600, 600), ss=2, fn=fn, light=(-0.5, 0.6, -0.65), ink=True)
    im = Image.fromarray(np.clip(img, 0, 255).astype("uint8"))
    d = ImageDraw.Draw(im)
    for p, seg in piv:
        sx, sy, _ = fn(*(np.array(p) + np.array(off[seg])))
        d.ellipse((sx - 5, sy - 5, sx + 5, sy + 5), outline=(220, 0, 0), width=2)
        d.text((sx + 160, sy - 6), "%s pivot" % {"Thigh": "HIP", "Shin": "KNEE", "Foot": "ANKLE"}[seg], fill=(200, 0, 0))
        d.line((sx + 6, sy, sx + 155, sy), fill=(220, 120, 120))
    d.text((6, 6), "Leg_R exploded: THIGH (hip->knee) / SHIN (knee->ankle) / FOOT; red rings = pivots", fill=(0, 0, 0))
    im.save(path)


if __name__ == "__main__":
    main()
