"""mech2 legs: the pieces, measured from the owner's sheet (refs/255.png, side detail refs/254.png).

UNITS: grid CELLS (1 cell = 0.816 studs; converted at export). FRAME: the RIGHT leg, origin at its
hip-joint centre, +Y up, -Z forward, +X = mech right = the leg's OUTER side (the left leg is the
mirror x -> -x). Every coordinate below is (screen px - anchor) / pitch from refs.py:
  FRONT  (right leg = the screen-LEFT leg, hip ball centre x = 111.5 px): x = (111.5 - px) / 28.44
  BACK   (right leg = the screen-RIGHT leg, hip ball centre x = 1293 px): x = (px - 1293) / 28.44
  SIDE   (hip ball centre x = 699.5 px; the toe points to screen left):  z = (px - 699.5) / 28.44
  all    (hip ball centre y = 13 px of 255.png = 20 of 254.png):          y = (13 - py) / 29.08
  e.g. "(130,408)s" below = pixel (130, 408) of refs/zoom_side.png, the 5x zoom of the sheet
  columns 590..780 (zoom_front: 55..170, zoom_back: 1235..1355) with 7 rows of 254.png on top,
  i.e. sheet px (590 + 130/5, 408/5 - 7). "f" = zoom_front, "b" = zoom_back. Most numbers were read off those 5x zooms (refs/zoom_*.png,
  regenerated by measure.py) and then trimmed against the silhouette table measure.py prints
  (fg extents every 0.25 cell), until the render's IoU per view passed 0.92.
Hip ball centre: side grey blob x 670..725 (widest rows y 7..15 -> centre px 699.5, y 13), radius
25 px = 0.86 cell; front balls centred x 111.5 / 247.5 px, back 1157 / 1293 px.
Ground (all soles): y px 314.5 -> Y_GROUND = (13 - 314.5) / 29.08 = -10.368 cells.
"""
from blocks import block, cylinder_x, sphere

YG = -10.368  # ground (sole) height in the leg frame, cells

# joint centres in the leg frame (cells)
HIP = (0.0, 0.0, 0.0)
# knee: middle of the leg's cross-section at the thigh/shin seam (front: x 1.32..-0.65 at y -5.5;
# side: z -0.83..1.35 at y -5.5, minus the back panel) -> (0.35, -5.4, 0.2)
KNEE = (0.35, -5.4, 0.2)
# ankle: centre of the SIDE view's grey ankle disc (5x zoom (515..640, 1340..1530)s -> z 0.2,
# y -9.25, about 0.6 cell radius); x = middle of the foot in FRONT (-0.38..1.64 at y -10 -> 0.62)
ANKLE = (0.62, -9.25, 0.2)


def pieces():
    """-> list of (segment, colour, name, Mesh) for the RIGHT leg in cells."""
    P = []

    def add(seg, col, name, m):
        P.append((seg, col, name, m))

    # ------------------------------------------------------------------ THIGH
    add("Thigh", "Joint", "hip_ball", sphere(HIP, 0.86))

    # White thigh plate. SIDE: a tilted square leaning forward, corners A (355,140)s top,
    # B (130,408)s front, C (400,720)s bottom, D = A + (C - B) = (625,452)s (behind the gold guard).
    thigh_side = [(-1.36, -0.28), (-2.94, -2.12), (-1.04, -4.26), (0.54, -2.42)]
    # FRONT: V-notched top (outer corner (35,150)f -> (1.78,-0.38), inner corner (495,175)f ->
    # (-1.48,-0.52), notch bottom where the gold shows (255,300)f -> (0.25,-1.38)), V point at the
    # bottom (tip (238,715)f -> (0.31,-4.23); sides (145,620)f / (360,625)f at y -3.55).
    # Split at the notch into two y-monotone halves; their shared edge is the plate's centre ridge.
    add("Thigh", "White", "thigh_plate_out", block(
        thigh_side, [(1.78, -0.38), (1.68, -1.0), (1.3, -2.0), (1.07, -3.0), (1.0, -3.55), (0.30, -4.23), (0.25, -1.38)],
        cf=0.18, cb=0.1, pf=0.22, ridge=0.0))
    add("Thigh", "White", "thigh_plate_in", block(
        thigh_side, [(0.25, -1.38), (0.30, -4.23), (-0.6, -3.55), (-0.71, -3.0), (-1.03, -2.0), (-1.48, -0.52)],
        cf=0.18, cb=0.1, pf=0.22, ridge=1.0))

    # Gold collar filling the plate's V notch exactly (its lower edges = the notch edges; FRONT gold
    # top (85,100)f..(360,85)f, bottom tip (255,300)f) and as the gold spike in front of the plate's top corner in SIDE
    # ((295,95)s (245,200)s (250,245)s -> z -1.78..-2.13, y 0.03..-1.0).
    add("Thigh", "Gold", "thigh_collar", block(
        [(-1.80, 0.06), (-1.45, 0.06), (-1.0, -0.35), (-1.0, -1.45), (-2.0, -1.1), (-2.12, -0.6)],
        [(1.45, 0.06), (-0.6, 0.08), (-1.45, -0.5), (0.25, -1.40), (1.75, -0.36)],
        cf=0.12, cb=0.1))

    # Big rounded gold hip/thigh guard on the OUTER side. SIDE outline (rounded lozenge):
    # top (735,100)s, back (870,240)s, (770,460)s, rounded bottom (430,560)s..(480,610)s, front
    # (418,420)s, blue edge (610,190)s; FRONT: the outer gold strip (x 1.0..1.68, table rows).
    guard_side = [(1.32, 0.0), (2.26, -0.96), (1.56, -2.48), (0.3, -3.35), (-0.45, -3.5), (-0.85, -3.05),
                  (-0.91, -2.3), (-0.75, -1.85), (-0.48, -1.58), (0.44, -0.62)]
    # Lower gold side plate (thigh back/side, under the guard): (550,640)s (580,915)s (625,945)s
    # (700,955)s; back edge from the side table (y -3: 1.71, -3.5: 1.81, -4: 1.92, -5: 1.56, -5.5: 1.35)
    lower_side = [(0.0, -2.5), (1.56, -2.48), (1.71, -3.0), (1.81, -3.5), (1.92, -4.1), (1.81, -4.5),
                  (1.56, -5.0), (1.35, -5.5), (1.07, -5.88), (0.54, -5.81), (0.22, -5.6), (0.01, -3.71)]
    outer_front = [(1.0, 0.02), (1.45, 0.05), (1.68, -0.6), (1.66, -3.0), (1.56, -3.5), (1.38, -4.0),
                   (1.42, -5.0), (1.32, -5.6), (1.1, -5.9), (0.98, -5.9)]
    add("Thigh", "Gold", "guard_out", block(guard_side, outer_front, cf=0.16, cb=0.22))
    add("Thigh", "Gold", "lower_out", block(lower_side, [(0.98, -2.4), (1.66, -2.4), (1.66, -3.0), (1.56, -3.5),
                                                        (1.38, -4.0), (1.42, -5.0), (1.32, -5.6), (1.1, -5.9),
                                                        (0.98, -5.9)], cf=0.12, cb=0.18))
    # same guard on the INNER side (FRONT inner gold strip; BACK inner gold column x -1.72..-0.95)
    inner_front = [(-0.6, -0.1), (-1.0, 0.0), (-1.45, 0.0), (-1.72, -0.4), (-1.67, -1.0), (-1.53, -2.0),
                   (-1.39, -3.0), (-1.25, -3.5), (-1.0, -4.0), (-0.93, -4.5), (-0.83, -5.0), (-0.72, -5.5),
                   (-0.65, -5.85), (-0.6, -5.85)]
    add("Thigh", "Gold", "guard_in", block(guard_side, inner_front, cf=0.16, cb=0.22))
    add("Thigh", "Gold", "lower_in", block(lower_side, inner_front, cf=0.12, cb=0.18))

    # Blue under-suit core of the thigh: BACK blue window (175,195)b..(405,470)b -> x -0.95..0.8,
    # y -0.65..-2.62; SIDE blue triangle (440,215)s (610,195)s (500,315)s between plate and guard.
    add("Thigh", "Blue", "thigh_core", block(
        [(-0.8, -0.45), (0.6, -0.45), (1.3, -1.0), (1.3, -5.6), (0.2, -5.9), (-0.2, -5.0), (-0.45, -3.6), (-0.75, -1.6)],
        [(-0.95, -0.45), (0.85, -0.45), (0.85, -5.8), (-0.6, -5.8)], cf=0.1, cb=0.1))
    # Gold rear plate under the blue window (BACK gold band y -2.62..-4.05)
    add("Thigh", "Gold", "thigh_rear", block(
        [(0.0, -2.55), (1.45, -2.55), (1.58, -3.0), (1.62, -4.1), (0.0, -4.1)],
        [(-1.0, -2.55), (1.0, -2.55), (1.0, -4.1), (-1.0, -4.1)], cf=0.1, cb=0.12))
    # Knee-back trapezoid panel: gold frame (BACK (175,745)b..(465,975)b) with a blue inset
    # ((240,745)b (370,742)b (410,945)b (250,960)b -> x -0.35..0.56 top, -0.28..0.85 bottom).
    knee_back_side = [(0.2, -4.0), (1.72, -4.0), (1.78, -4.5), (1.5, -5.0), (1.3, -5.5), (1.05, -6.05), (0.2, -6.05)]
    add("Thigh", "Gold", "kneeback_top", block(knee_back_side, [(-0.9, -4.0), (1.25, -4.0), (1.25, -4.43), (-0.9, -4.43)], cf=0.08, cb=0.08))
    add("Thigh", "Gold", "kneeback_in", block(knee_back_side, [(-0.91, -4.43), (-0.35, -4.43), (-0.28, -5.95), (-0.77, -5.95)], cf=0.08, cb=0.08))
    add("Thigh", "Gold", "kneeback_out", block(knee_back_side, [(0.56, -4.43), (1.25, -4.43), (1.22, -5.95), (0.85, -5.95)], cf=0.08, cb=0.08))
    add("Thigh", "Gold", "kneeback_bottom", block(knee_back_side, [(-0.8, -5.85), (1.23, -5.85), (1.22, -6.05), (-0.78, -6.05)], cf=0.06, cb=0.06))
    add("Thigh", "Blue", "kneeback_inset", block(
        [(0.2, -4.4), (1.55, -4.4), (1.6, -4.6), (1.3, -5.1), (1.12, -5.5), (0.92, -5.95), (0.2, -5.95)],
        [(-0.36, -4.4), (0.6, -4.4), (0.88, -5.95), (-0.3, -5.95)], cf=0.05, cb=0.05))
    # White knee block between the thigh plate's V tip and the shin plate's V tip (FRONT x -0.62..1.0 between the gold strips,
    # SIDE (488,620)s (550,640)s (580,915)s (460,840)s (430,700)s)
    add("Thigh", "White", "knee_block", block(
        [(-0.42, -3.58), (0.01, -3.71), (0.22, -5.6), (-0.62, -5.12), (-0.83, -4.13)],
        [(1.0, -3.4), (-0.62, -3.4), (-0.6, -5.6), (1.05, -5.6)], cf=0.12, cb=0.05, pf=0.12, ridge=0.5))

    # ------------------------------------------------------------------ SHIN
    add("Shin", "Joint", "knee_axle", cylinder_x((KNEE[1], KNEE[2]), 0.4, -0.45, 0.95))
    # White shin plate. SIDE: top (460,845)s, front knee (330,1160)s, (355,1245)s, bottom (460,1465)s,
    # back edge x ~0.62 ((640,955)s..(620,1335)s). FRONT: V tip at the top (238,822)f -> (0.31,-4.97),
    # widening to x 1.92 / -0.86 at y -8.3 (table), arch over the blue ankle (apex (210,1175)f ->
    # (0.51,-7.39), outer side (130,1300)f (75,1360)f (40,1440)f, inner (290,1290)f (330,1380)f (345,1440)f).
    shin_side = [(-0.62, -5.1), (0.22, -5.6), (0.62, -5.9), (0.65, -7.5), (0.55, -8.45), (-0.62, -9.4),
                 (-1.36, -7.88), (-1.53, -7.3)]
    add("Shin", "White", "shin_plate", block(shin_side, [(0.31, -4.97), (1.32, -5.55), (1.39, -6.0), (1.53, -6.5),
                                                         (1.64, -7.0), (1.70, -7.39), (-0.76, -7.39), (-0.72, -7.0),
                                                         (-0.65, -6.0), (-0.65, -5.6)],
                                             cf=0.16, cb=0.1, pf=0.2, ridge=0.42))
    add("Shin", "White", "shin_flank_out", block(shin_side, [(1.70, -7.39), (1.78, -7.5), (1.88, -8.0), (1.92, -8.4),
                                                             (1.88, -9.0), (1.85, -9.45), (1.72, -9.45), (1.70, -9.2),
                                                             (1.45, -8.67), (1.07, -8.25), (0.51, -7.39)],
                                                 cf=0.08, cb=0.06))
    add("Shin", "White", "shin_flank_in", block(shin_side, [(0.51, -7.39), (-0.05, -8.2), (-0.33, -8.8), (-0.45, -9.2),
                                                            (-0.6, -9.42), (-0.69, -9.25), (-0.83, -8.5), (-0.86, -8.25),
                                                            (-0.79, -7.5), (-0.76, -7.39)],
                                                cf=0.08, cb=0.06))
    # Blue calf (SIDE blue strip (630,955)s (700,965)s (725,1180)s (665,1230)s; BACK blue
    # (220,985)b (440,975)b down to (210,1405)b / (500,1350)b)
    add("Shin", "Blue", "calf", block(
        [(0.3, -5.8), (1.1, -5.85), (1.2, -6.6), (1.26, -7.4), (1.1, -7.75), (0.8, -7.95), (0.75, -8.9), (0.2, -8.9)],
        [(-0.5, -5.85), (1.06, -5.85), (1.48, -8.6), (1.3, -8.95), (-0.56, -8.95)], cf=0.1, cb=0.14))
    # Blue ankle front, seen through the shin plate's arch (FRONT (210,1215)f (120,1290)f (130,1360)f
    # (275,1365)f (300,1320)f; SIDE patch (340,1260)s..(400,1345)s)
    add("Shin", "Blue", "ankle_front", block(
        [(-1.3, -7.55), (-0.4, -7.55), (-0.4, -8.85), (-1.0, -8.85), (-1.48, -8.3)],
        [(0.5, -7.55), (1.15, -8.1), (1.2, -8.6), (1.0, -8.85), (0.0, -8.85), (-0.15, -8.4), (0.1, -7.9)],
        cf=0.1, cb=0.05))
    # White Achilles plate / back spur (SIDE (760,1135)s (850,1270)s (830,1395)s (735,1340)s,
    # plus the white sliver (665,1230)s..(740,1190)s; BACK white box (275,1140)b..(440,1385)b)
    add("Shin", "White", "achilles", block(
        [(1.49, -7.12), (2.12, -8.05), (1.98, -8.9), (1.31, -8.53), (0.9, -8.3), (0.85, -7.75), (1.35, -7.5)],
        [(0.0, -7.2), (1.05, -7.2), (1.1, -8.95), (-0.05, -8.95)], cf=0.1, cb=0.2, pb=0.12, ridge=0.5))
    # Grey ankle: disc (SIDE (515..640, 1340..1530)s -> centre z 0.2, y -9.25, r 0.58) and the
    # grey cover above it ((620,1330)s (670,1285)s (735,1335)s (640,1395)s)
    add("Shin", "Joint", "ankle_disc", cylinder_x((ANKLE[1], ANKLE[2]), 0.58, -0.3, 1.55))
    add("Shin", "Joint", "ankle_cover", block(
        [(0.86, -8.12), (1.32, -8.49), (0.65, -8.92), (0.45, -8.5)],
        [(-0.1, -8.1), (1.55, -8.1), (1.55, -8.95), (-0.1, -8.95)], cf=0.06, cb=0.06))

    # ------------------------------------------------------------------ FOOT
    # White toe plate: SIDE (345,1345)s (400,1345)s (460,1468)s .. toe (50,1590)s (65,1612)s;
    # FRONT white foot x -0.4..1.64 with its lower corners cut where the gold toe shows
    add("Foot", "White", "toe_plate", block(
        [(-1.43, -8.56), (-1.04, -8.56), (-0.3, -9.6), (-0.9, YG), (-3.45, YG), (-3.58, -10.27)],
        [(-0.35, -8.75), (1.62, -8.75), (1.64, -9.85), (1.33, YG), (0.0, YG), (-0.4, -9.7)],
        cf=0.12, cb=0.06, pf=0.1, ridge=0.5))
    # Gold toe tip (SIDE (230,1612)s (265,1555)s (370,1548)s (480,1445)s (515,1445)s (520,1500)s
    # (430,1612)s; FRONT gold corners (50..90, 1530..1610)f and (285..345, 1500..1610)f)
    add("Foot", "Gold", "toe_tip", block(
        [(-0.48, -9.25), (-0.23, -9.25), (-0.2, -9.63), (-0.83, YG), (-2.24, YG), (-1.99, -10.0), (-1.25, -9.96)],
        [(-0.42, -9.25), (1.66, -9.25), (1.66, YG), (-0.42, YG)], cf=0.1, cb=0.06))
    # Gold heel block (SIDE (640,1390)s (740,1350)s (820,1470)s (770,1612)s (620,1612)s (585,1550)s
    # (630,1500)s; BACK gold block (240,1395)b..(520,1612)b -> x -0.35..1.6, y -8.95..ground)
    add("Foot", "Gold", "heel", block(
        [(1.35, -8.6), (1.91, -9.42), (1.56, YG), (0.51, YG), (0.26, -9.97), (0.58, -9.63), (0.65, -8.87)],
        [(-0.35, -8.6), (1.6, -8.6), (1.62, YG), (-0.38, YG)], cf=0.12, cb=0.16))
    return P
