"""Re-runnable generator for the mech2 HEAD meshes.

    python build.py            # writes ../Head_*.obj + ../meta.json, then runs verify (renders + IoU)
    python build.py --no-verify

Geometry lives in geom.py (grid cells); this scales to studs (1 cell = 0.816
studs), checks the shells are closed and writes OBJ (+UVs, 1 repeat = 4 studs).
meshlib.py is a copy of the legs helper's toolkit (mech2/legs/source/meshlib.py)
so both parts share UV / OBJ conventions.
"""
import json
import os
import sys

import numpy as np

import geom
from meshlib import Mesh, open_edges, write_obj, weld

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, ".."))
CELL = 0.816  # studs per grid cell

COLOURS = {  # name -> (file, RGB)
    "Gold": ("Head_Gold.obj", (212, 169, 58)),
    "White": ("Head_White.obj", (236, 236, 236)),
    "Blue": ("Head_Blue.obj", (47, 111, 191)),
    "Neck": ("Head_Neck.obj", (120, 122, 128)),
}


def scaled(m, s):
    o = Mesh()
    o.v = [[p[0] * s, p[1] * s, p[2] * s] for p in m.v]
    o.f = list(m.f)
    return o


def n_shells(m):
    parent = list(range(len(m.v)))

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a
    for a, b, c in m.f:
        for u, v in ((a, b), (b, c)):
            ru, rv = find(u), find(v)
            if ru != rv:
                parent[ru] = rv
    return len({find(f[0]) for f in m.f})


def main():
    parts = geom.all_parts()
    meta = {"units": "studs", "cell_studs": CELL, "axes": "+Y up, -Z forward (face), X symmetric",
            "origin": "neck base = attachment to the torso (top of the torso collar); neck plug runs 0.49 studs below it",
            "attach_point": [0, 0, 0], "pieces": {}}
    allv = []
    for name, m in parts.items():
        fn, rgb = COLOURS[name]
        ms = scaled(m, CELL)
        oe = open_edges(ms)
        assert oe == 0, (name, oe)
        tris, stretch, islands = write_obj(os.path.join(OUT, fn), ms,
                                           header="mech2 head - %s (studs, origin = neck base, -Z forward)\ncolour RGB %s\ngenerated by source/build.py" % (name, rgb))
        V, F = ms.arrays()
        lo, hi = V.min(0), V.max(0)
        allv.append(V)
        meta["pieces"][name] = {
            "file": fn, "rgb": list(rgb), "hex": "#%02X%02X%02X" % rgb, "tris": int(tris), "verts": len(V),
            "shells": n_shells(ms), "open_edges": oe, "uv_islands": islands, "uv_max_stretch": round(stretch, 3),
            "bbox_min": [round(float(x), 3) for x in lo], "bbox_max": [round(float(x), 3) for x in hi],
            "size": [round(float(x), 3) for x in hi - lo],
            "centre": [round(float(x), 3) for x in (hi + lo) / 2],
        }
        print("%-6s %-15s tris %4d shells %2d open %d stretch %.3f size %s" % (
            name, fn, tris, meta["pieces"][name]["shells"], oe, stretch, meta["pieces"][name]["size"]))
    A = np.concatenate(allv)
    meta["head_bbox_min"] = [round(float(x), 3) for x in A.min(0)]
    meta["head_bbox_max"] = [round(float(x), 3) for x in A.max(0)]
    meta["head_size"] = [round(float(x), 3) for x in A.max(0) - A.min(0)]
    meta["visor"] = "none - the art shows no eyes: the face is the gold V brow/visor plate over two white chin chevrons"
    if "--no-verify" not in sys.argv:
        import verify
        res = verify.compare(parts)
        verify.depth_check(parts)
        verify.ortho_renders(parts)
        meta["iou"] = res
        for k, v in res.items():
            print(k, v)
    meta["depth"] = depth_numbers()
    with open(os.path.join(OUT, "meta.json"), "w") as fh:
        json.dump(meta, fh, indent=2)


def depth_numbers():
    """Key depth facts (studs), straight from the geometry constants."""
    c = CELL
    b = geom.BLADES
    d = {
        "prow_z (brow/visor tip)": round(-2.52 * c, 3),
        "band_temple_z (brow ends at the cheek sides)": round(0.18 * c, 3),
        "face_projection_prow_vs_temples": round((0.18 + 2.52) * c, 3),
        "crown_ridge_z_at_Y2.31": round(-1.40 * c, 3),
        "crown_back_plane_z": round(geom.CROWN_BACK * c, 3),
        "skull_back_z": round(1.86 * c, 3),
        "chin_upper_plate_front_z": round(-1.50 * c, 3),
        "chin_lower_plate_front_z (top..tip)": [round(-1.38 * c, 3), round((-1.38 - 0.10 * 0.60) * c, 3)],
        "band_overhang_over_chin": round((1.62 - 1.50) * c, 3),
    }
    for k, v in b.items():
        rz = min(v["Rt"][2], v["Rb"][2])
        d["%s_root_z..tip_z" % k] = [round(rz * c, 3), round(v["T"][2] * c, 3)]
        mid = (np.array(v["Rt"]) + np.array(v["Rb"])) / 2
        ang = np.degrees(np.arctan2(v["T"][1] - mid[1], v["T"][2] - mid[2]))
        d["%s_sweep_angle_deg (side view, from horizontal)" % k] = round(float(ang), 1)
        d["%s_tip_behind_skull_back" % k] = round((v["T"][2] - 1.86) * c, 3)
    return d


if __name__ == "__main__":
    main()
