# Generates src/shared/GearMeta.luau from assets/gear3d/meta.json (node bbox
# centres, joint pivots, weapon grip offsets) for ArmorBuilder's fitting.
import json, os
root = os.path.join(os.path.dirname(__file__), "..")
m = json.load(open(os.path.join(root, "assets/gear3d/meta.json")))
def v(x): return "Vector3.new(%.4f, %.4f, %.4f)" % tuple(x)
def c(n): return [(a + b) / 2 for a, b in zip(n["bbox_min"], n["bbox_max"])]
L = ["--!strict", "-- GENERATED by tools/make_gear_meta_luau.py from assets/gear3d/meta.json.",
     "-- Source frame (studs, Y up, front -Z, +X = right): per tier the bbox centre of every node and",
     "-- the joint pivots; per weapon the bbox centre relative to the grip (origin).", "",
     "local GearMeta = {}", "", "GearMeta.Tiers = {"]
for key in sorted(m["tiers"]):
    t = m["tiers"][key]
    L.append("\t[%d] = {" % int(key[1:]))
    L.append("\t\tcentres = {")
    for n, d in sorted(t["nodes"].items()):
        L.append("\t\t\t%s = %s," % (n, v(c(d))))
    L.append("\t\t},")
    L.append("\t\tpivots = {")
    for n, p in sorted(t["pivots"].items()):
        L.append("\t\t\t%s = %s," % (n, v(p)))
    L.append("\t\t},")
    L.append("\t},")
L += ["} :: { [number]: { centres: { [string]: Vector3 }, pivots: { [string]: Vector3 } } }", "", "GearMeta.WeaponCentres = {"]
for n, d in sorted(m["weapons"]["nodes"].items()):
    g = d.get("grip", [0, 0, 0])
    L.append("\t%s = %s," % (n, v([a - b for a, b in zip(c(d), g)])))
L += ["} :: { [string]: Vector3 }", "", "return GearMeta", ""]
open(os.path.join(root, "src/shared/GearMeta.luau"), "w", newline="\n").write("\n".join(L))
print("ok", len(m["tiers"]), "tiers")
